import React,{useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {ArrowUpRight,Briefcase,BookOpen,CalendarDays,Clock3,Sparkles} from 'lucide-react'
import {supabase} from '../lib/supabase'

export default function Dashboard({profile}){const [ops,setOps]=useState([]),[events,setEvents]=useState([]),[apps,setApps]=useState(0)
 useEffect(()=>{(async()=>{const [o,e,a]=await Promise.all([supabase.from('opportunities').select('*').eq('is_active',true).order('deadline',{ascending:true}).limit(4),supabase.from('events').select('*').gte('event_date',new Date().toISOString()).order('event_date').limit(3),supabase.from('applications').select('id',{count:'exact',head:true})]);setOps(o.data||[]);setEvents(e.data||[]);setApps(a.count||0)})()},[])
 return <div><div className="hero"><div><span className="eyebrow">STUDENT DASHBOARD</span><h1>Good to see you, {profile?.full_name?.split(' ')[0]||'there'}.</h1><p>Stay on top of the opportunities and campus activities that matter to you.</p></div><Link className="primary" to="/opportunities">Explore opportunities <ArrowUpRight size={17}/></Link></div>
 <div className="stat-grid"><Stat icon={Briefcase} label="Open opportunities" value={ops.length||'—'}/><Stat icon={ClipboardIcon} label="Your applications" value={apps}/><Stat icon={CalendarDays} label="Upcoming events" value={events.length}/><Stat icon={BookOpen} label="Resources" value="Explore"/></div>
 <div className="section-head"><div><h2>Recommended opportunities</h2><p>Fresh openings with upcoming deadlines.</p></div><Link to="/opportunities" className="text-link">View all <ArrowUpRight size={15}/></Link></div>
 <div className="card-grid">{ops.map(o=><Opportunity key={o.id} o={o}/>)}</div>
 <div className="two-col"><div><div className="section-head compact"><div><h2>Upcoming events</h2><p>Don't miss what is happening on campus.</p></div><Link to="/events" className="text-link">See all</Link></div><div className="list-card">{events.map(e=><div className="event-row" key={e.id}><div className="date-tile"><b>{new Date(e.event_date).getDate()}</b><span>{new Date(e.event_date).toLocaleString('en',{month:'short'})}</span></div><div><b>{e.title}</b><p>{e.location||'Campus'} · {new Date(e.event_date).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div></div>)}</div></div><div className="tip-card"><div className="tip-icon"><Sparkles size={21}/></div><span className="eyebrow">COMING SOON</span><h3>Personalized recommendations</h3><p>Once your profile is complete, CampusConnect will use your skills and interests to surface relevant internships, hackathons and scholarships.</p><Link to="/profile" className="text-link">Complete profile <ArrowUpRight size={15}/></Link></div></div>
 </div>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="stat-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Opportunity({o}){return <Link to="/opportunities" className="op-card"><div className="op-top"><span className="pill">{o.type}</span><Clock3 size={15}/></div><h3>{o.title}</h3><p>{o.organization} · {o.location||'Remote'}</p><div className="op-foot"><span>Deadline {o.deadline?new Date(o.deadline).toLocaleDateString(): '—'}</span><ArrowUpRight size={16}/></div></Link>}
function ClipboardIcon(props){return <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="5" y="5" width="14" height="16" rx="2"/><path d="M9 5V3h6v2M8 11h8M8 15h6"/></svg>}
