import React,{useEffect,useState} from 'react'
import {Search,Bookmark,ExternalLink,MapPin,CalendarClock,Filter} from 'lucide-react'
import {supabase} from '../lib/supabase'

export default function Opportunities(){const [items,setItems]=useState([]),[q,setQ]=useState(''),[type,setType]=useState('All'),[saved,setSaved]=useState(new Set()),[applied,setApplied]=useState(new Set()),[loading,setLoading]=useState(true)
 useEffect(()=>{load()},[]);async function load(){setLoading(true);const {data}=await supabase.from('opportunities').select('*').eq('is_active',true).order('deadline',{ascending:true});setItems(data||[]);const {data:u}=await supabase.auth.getUser();if(u.user){const [{data:s},{data:a}]=await Promise.all([supabase.from('bookmarks').select('opportunity_id').eq('user_id',u.user.id),supabase.from('applications').select('opportunity_id').eq('user_id',u.user.id)]);setSaved(new Set((s||[]).map(x=>x.opportunity_id)));setApplied(new Set((a||[]).map(x=>x.opportunity_id)))}setLoading(false)}
 const types=['All',...new Set(items.map(x=>x.type).filter(Boolean))];const filtered=items.filter(x=>(type==='All'||x.type===type)&&(`${x.title} ${x.organization} ${x.description||''} ${x.skills||''}`).toLowerCase().includes(q.toLowerCase()))
 async function apply(id){const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('applications').insert({user_id:u.user.id,opportunity_id:id});if(!error||error.code==='23505')setApplied(s=>new Set(s).add(id));else alert(error.message)}
 async function toggle(id){const {data:u}=await supabase.auth.getUser();if(!u.user)return;if(saved.has(id)){await supabase.from('bookmarks').delete().eq('user_id',u.user.id).eq('opportunity_id',id);setSaved(s=>{const n=new Set(s);n.delete(id);return n})}else{await supabase.from('bookmarks').insert({user_id:u.user.id,opportunity_id:id});setSaved(s=>new Set(s).add(id))}}
 return <div><div className="page-head"><div><span className="eyebrow">DISCOVER</span><h1>Opportunities</h1><p>Internships, jobs, scholarships and competitions curated for students.</p></div></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search opportunities, skills or companies..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="filter"><Filter size={16}/><select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></div></div>{loading?<div className="loading-grid">Loading opportunities...</div>:<div className="opportunity-grid">{filtered.map(o=><article className="large-op" key={o.id}><div className="op-top"><span className="pill">{o.type}</span><button className={saved.has(o.id)?'save saved':'save'} onClick={()=>toggle(o.id)}><Bookmark size={18} fill={saved.has(o.id)?'currentColor':'none'}/></button></div><h2>{o.title}</h2><p className="org">{o.organization}</p><p>{o.description||'Opportunity details are available on the application page.'}</p><div className="meta"><span><MapPin size={15}/>{o.location||'Remote'}</span><span><CalendarClock size={15}/>Deadline {o.deadline?new Date(o.deadline).toLocaleDateString():'TBA'}</span></div><div className="skill-row">{(o.skills||'Students').split(',').slice(0,4).map(s=><span key={s}>{s.trim()}</span>)}</div><div className="apply-actions"><button className={applied.has(o.id)?'secondary full':'primary full'} onClick={()=>apply(o.id)}>{applied.has(o.id)?'Application tracked':'Track application'}</button>{o.apply_url&&<a href={o.apply_url} target="_blank" rel="noreferrer" className="text-link apply-link">Open application <ExternalLink size={15}/></a>}</div></article>)}</div>}{!loading&&!filtered.length&&<div className="empty"><Search size={24}/><h3>No opportunities found</h3><p>Try another search or category.</p></div>}</div>}
